# Generated by Django 5.1 on 2024-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_onwer_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
